packages:
  - 'apps/*'
allowBuilds:
  esbuild: true
  ffmpeg-static: true
  msw: true
  protobufjs: true
  sharp: true
  unrs-resolver: true
onlyBuiltDependencies:
  - esbuild
  - ffmpeg-static
  - msw
  - sharp
  - unrs-resolver
