import type {
  TrackingComponentCategory,
  TrackingEventCategory,
  TrackingEventScope,
} from '@/lib/db/types';

export interface EventCatalogEntry {
  name: string;
  category: TrackingEventCategory;
  scope: TrackingEventScope;
  description: string;
  isConversion: boolean;
  applicableCategories: TrackingComponentCategory[];
  defaultProviders: string[];
  paramsSchema: Record<string, unknown>;
}

const ITEM_SCHEMA = {
  type: 'object',
  required: ['item_id', 'item_name'],
  properties: {
    item_id: { type: 'string' },
    item_name: { type: 'string' },
    item_brand: { type: 'string' },
    item_category: { type: 'string' },
    item_variant: { type: 'string' },
    price: { type: 'number' },
    quantity: { type: 'number' },
    currency: { type: 'string' },
  },
};

function ecommerceParams(extras: Record<string, unknown> = {}): Record<string, unknown> {
  return {
    type: 'object',
    properties: {
      currency: { type: 'string' },
      value: { type: 'number' },
      items: { type: 'array', items: ITEM_SCHEMA },
      ...extras,
    },
  };
}

const ALL_PROVIDERS = ['meta', 'tiktok', 'google_ga4', 'google_ads', 'snap', 'pinterest'];
const COMMERCE_PROVIDERS = ['meta', 'tiktok', 'google_ga4', 'google_ads', 'snap', 'pinterest'];

export const EVENT_CATALOG: EventCatalogEntry[] = [
  {
    name: 'page_view',
    category: 'page',
    scope: 'web',
    description: 'Affichage d\u2019une page (route ou changement client-side)',
    isConversion: false,
    applicableCategories: ['section_hero', 'section_content', 'navigation'],
    defaultProviders: ALL_PROVIDERS,
    paramsSchema: {
      type: 'object',
      required: ['page_path'],
      properties: {
        page_path: { type: 'string' },
        page_title: { type: 'string' },
        page_referrer: { type: 'string' },
      },
    },
  },
  {
    name: 'scroll_depth',
    category: 'engagement',
    scope: 'web',
    description: 'Profondeur de scroll (paliers 25/50/75/90)',
    isConversion: false,
    applicableCategories: ['section_content', 'section_hero', 'section_faq'],
    defaultProviders: ['google_ga4'],
    paramsSchema: {
      type: 'object',
      required: ['percent_scrolled'],
      properties: { percent_scrolled: { type: 'number', enum: [25, 50, 75, 90] } },
    },
  },
  {
    name: 'click',
    category: 'engagement',
    scope: 'web',
    description: 'Clic g\u00e9n\u00e9rique (CTA, lien, bouton)',
    isConversion: false,
    applicableCategories: ['cta_primary', 'cta_secondary', 'cta_ghost', 'navigation', 'banner'],
    defaultProviders: ['google_ga4'],
    paramsSchema: {
      type: 'object',
      properties: {
        link_text: { type: 'string' },
        link_url: { type: 'string' },
        outbound: { type: 'boolean' },
      },
    },
  },
  {
    name: 'select_content',
    category: 'engagement',
    scope: 'web',
    description: 'S\u00e9lection d\u2019un contenu (carte, item, lien)',
    isConversion: false,
    applicableCategories: ['card', 'list_item', 'section_content', 'tab', 'accordion'],
    defaultProviders: ['google_ga4'],
    paramsSchema: {
      type: 'object',
      required: ['content_type'],
      properties: {
        content_type: { type: 'string' },
        content_id: { type: 'string' },
      },
    },
  },
  {
    name: 'share',
    category: 'engagement',
    scope: 'web',
    description: 'Partage de contenu',
    isConversion: false,
    applicableCategories: ['social_share'],
    defaultProviders: ['google_ga4'],
    paramsSchema: {
      type: 'object',
      properties: { method: { type: 'string' }, content_id: { type: 'string' } },
    },
  },
  {
    name: 'search',
    category: 'engagement',
    scope: 'web',
    description: 'Soumission d\u2019une recherche interne',
    isConversion: false,
    applicableCategories: ['search'],
    defaultProviders: ['google_ga4'],
    paramsSchema: {
      type: 'object',
      required: ['search_term'],
      properties: { search_term: { type: 'string' } },
    },
  },
  {
    name: 'video_start',
    category: 'engagement',
    scope: 'web',
    description: 'Lancement d\u2019une vid\u00e9o',
    isConversion: false,
    applicableCategories: ['media_video'],
    defaultProviders: ['google_ga4', 'meta'],
    paramsSchema: {
      type: 'object',
      properties: { video_title: { type: 'string' }, video_duration: { type: 'number' } },
    },
  },
  {
    name: 'video_progress',
    category: 'engagement',
    scope: 'web',
    description: 'Progression vid\u00e9o (10/25/50/75)',
    isConversion: false,
    applicableCategories: ['media_video'],
    defaultProviders: ['google_ga4'],
    paramsSchema: {
      type: 'object',
      required: ['video_percent'],
      properties: { video_percent: { type: 'number' }, video_title: { type: 'string' } },
    },
  },
  {
    name: 'video_complete',
    category: 'engagement',
    scope: 'web',
    description: 'Fin de lecture vid\u00e9o',
    isConversion: false,
    applicableCategories: ['media_video'],
    defaultProviders: ['google_ga4', 'meta'],
    paramsSchema: { type: 'object', properties: { video_title: { type: 'string' } } },
  },
  {
    name: 'file_download',
    category: 'engagement',
    scope: 'web',
    description: 'T\u00e9l\u00e9chargement d\u2019un fichier',
    isConversion: false,
    applicableCategories: ['cta_primary', 'cta_secondary'],
    defaultProviders: ['google_ga4'],
    paramsSchema: { type: 'object', properties: { file_name: { type: 'string' }, file_extension: { type: 'string' } } },
  },
  {
    name: 'form_start',
    category: 'engagement',
    scope: 'web',
    description: 'D\u00e9but d\u2019interaction avec un formulaire',
    isConversion: false,
    applicableCategories: ['form_input'],
    defaultProviders: ['google_ga4'],
    paramsSchema: { type: 'object', properties: { form_id: { type: 'string' } } },
  },
  {
    name: 'form_submit',
    category: 'engagement',
    scope: 'web',
    description: 'Soumission d\u2019un formulaire (sans conversion lead)',
    isConversion: false,
    applicableCategories: ['form_submit'],
    defaultProviders: ['google_ga4'],
    paramsSchema: { type: 'object', properties: { form_id: { type: 'string' } } },
  },
  {
    name: 'view_item_list',
    category: 'ecommerce',
    scope: 'web',
    description: 'Vue d\u2019une liste de produits',
    isConversion: false,
    applicableCategories: ['list_item', 'commerce_cart'],
    defaultProviders: COMMERCE_PROVIDERS,
    paramsSchema: ecommerceParams({ item_list_id: { type: 'string' }, item_list_name: { type: 'string' } }),
  },
  {
    name: 'select_item',
    category: 'ecommerce',
    scope: 'web',
    description: 'S\u00e9lection d\u2019un produit',
    isConversion: false,
    applicableCategories: ['list_item', 'card'],
    defaultProviders: COMMERCE_PROVIDERS,
    paramsSchema: ecommerceParams(),
  },
  {
    name: 'view_item',
    category: 'ecommerce',
    scope: 'both',
    description: 'Affichage d\u2019une fiche produit',
    isConversion: false,
    applicableCategories: ['section_hero', 'card', 'commerce_cart'],
    defaultProviders: COMMERCE_PROVIDERS,
    paramsSchema: ecommerceParams(),
  },
  {
    name: 'add_to_cart',
    category: 'ecommerce',
    scope: 'both',
    description: 'Ajout au panier',
    isConversion: false,
    applicableCategories: ['cta_primary', 'commerce_cart'],
    defaultProviders: COMMERCE_PROVIDERS,
    paramsSchema: ecommerceParams(),
  },
  {
    name: 'remove_from_cart',
    category: 'ecommerce',
    scope: 'web',
    description: 'Suppression du panier',
    isConversion: false,
    applicableCategories: ['commerce_cart'],
    defaultProviders: ['google_ga4'],
    paramsSchema: ecommerceParams(),
  },
  {
    name: 'view_cart',
    category: 'ecommerce',
    scope: 'web',
    description: 'Vue du panier',
    isConversion: false,
    applicableCategories: ['commerce_cart'],
    defaultProviders: COMMERCE_PROVIDERS,
    paramsSchema: ecommerceParams(),
  },
  {
    name: 'begin_checkout',
    category: 'ecommerce',
    scope: 'both',
    description: 'D\u00e9but du tunnel checkout',
    isConversion: true,
    applicableCategories: ['commerce_checkout', 'cta_primary'],
    defaultProviders: COMMERCE_PROVIDERS,
    paramsSchema: ecommerceParams(),
  },
  {
    name: 'add_shipping_info',
    category: 'ecommerce',
    scope: 'both',
    description: 'Ajout des infos de livraison',
    isConversion: false,
    applicableCategories: ['commerce_checkout', 'form_input'],
    defaultProviders: COMMERCE_PROVIDERS,
    paramsSchema: ecommerceParams({ shipping_tier: { type: 'string' } }),
  },
  {
    name: 'add_payment_info',
    category: 'ecommerce',
    scope: 'both',
    description: 'Ajout des infos de paiement',
    isConversion: false,
    applicableCategories: ['commerce_checkout'],
    defaultProviders: COMMERCE_PROVIDERS,
    paramsSchema: ecommerceParams({ payment_type: { type: 'string' } }),
  },
  {
    name: 'purchase',
    category: 'ecommerce',
    scope: 'both',
    description: 'Achat finalis\u00e9',
    isConversion: true,
    applicableCategories: ['commerce_checkout', 'section_content'],
    defaultProviders: COMMERCE_PROVIDERS,
    paramsSchema: ecommerceParams({ transaction_id: { type: 'string' }, tax: { type: 'number' }, shipping: { type: 'number' } }),
  },
  {
    name: 'refund',
    category: 'ecommerce',
    scope: 'server',
    description: 'Remboursement de commande',
    isConversion: false,
    applicableCategories: ['admin'],
    defaultProviders: ['google_ga4', 'meta'],
    paramsSchema: ecommerceParams({ transaction_id: { type: 'string' } }),
  },
  {
    name: 'view_promotion',
    category: 'ecommerce',
    scope: 'web',
    description: 'Vue d\u2019une promotion',
    isConversion: false,
    applicableCategories: ['banner', 'section_hero', 'card'],
    defaultProviders: ['google_ga4'],
    paramsSchema: {
      type: 'object',
      properties: { promotion_id: { type: 'string' }, promotion_name: { type: 'string' }, creative_slot: { type: 'string' } },
    },
  },
  {
    name: 'select_promotion',
    category: 'ecommerce',
    scope: 'web',
    description: 'Clic sur une promotion',
    isConversion: false,
    applicableCategories: ['banner', 'cta_primary', 'card'],
    defaultProviders: ['google_ga4'],
    paramsSchema: {
      type: 'object',
      properties: { promotion_id: { type: 'string' }, promotion_name: { type: 'string' } },
    },
  },
  {
    name: 'generate_lead',
    category: 'lead',
    scope: 'both',
    description: 'G\u00e9n\u00e9ration d\u2019un lead (formulaire complet)',
    isConversion: true,
    applicableCategories: ['form_submit', 'newsletter'],
    defaultProviders: ['meta', 'google_ga4', 'google_ads', 'tiktok', 'snap', 'pinterest'],
    paramsSchema: {
      type: 'object',
      properties: {
        currency: { type: 'string' },
        value: { type: 'number' },
        lead_id: { type: 'string' },
        method: { type: 'string' },
      },
    },
  },
  {
    name: 'sign_up',
    category: 'lead',
    scope: 'both',
    description: 'Cr\u00e9ation d\u2019un compte',
    isConversion: true,
    applicableCategories: ['form_submit'],
    defaultProviders: ['google_ga4', 'meta', 'tiktok'],
    paramsSchema: { type: 'object', properties: { method: { type: 'string' } } },
  },
  {
    name: 'login',
    category: 'lead',
    scope: 'web',
    description: 'Connexion utilisateur',
    isConversion: false,
    applicableCategories: ['form_submit'],
    defaultProviders: ['google_ga4'],
    paramsSchema: { type: 'object', properties: { method: { type: 'string' } } },
  },
  {
    name: 'fg_journal_read_75',
    category: 'custom',
    scope: 'web',
    description: 'Lecture article journal \u2265 75 %',
    isConversion: false,
    applicableCategories: ['section_content'],
    defaultProviders: ['google_ga4'],
    paramsSchema: { type: 'object', properties: { article_id: { type: 'string' } } },
  },
  {
    name: 'fg_journal_read_100',
    category: 'custom',
    scope: 'web',
    description: 'Lecture article journal compl\u00e8te',
    isConversion: false,
    applicableCategories: ['section_content'],
    defaultProviders: ['google_ga4'],
    paramsSchema: { type: 'object', properties: { article_id: { type: 'string' } } },
  },
  {
    name: 'fg_section_view',
    category: 'custom',
    scope: 'web',
    description: 'Section vue (intersection 50 % \u00e9cran)',
    isConversion: false,
    applicableCategories: ['section_hero', 'section_content', 'section_faq', 'section_testimonial'],
    defaultProviders: ['google_ga4'],
    paramsSchema: { type: 'object', properties: { section_id: { type: 'string' } } },
  },
  {
    name: 'fg_faq_view',
    category: 'custom',
    scope: 'web',
    description: 'Ouverture d\u2019une question FAQ',
    isConversion: false,
    applicableCategories: ['accordion', 'section_faq'],
    defaultProviders: ['google_ga4'],
    paramsSchema: { type: 'object', properties: { faq_id: { type: 'string' } } },
  },
  {
    name: 'fg_composition_open',
    category: 'custom',
    scope: 'web',
    description: 'Ouverture du panneau composition produit',
    isConversion: false,
    applicableCategories: ['accordion', 'modal'],
    defaultProviders: ['google_ga4'],
    paramsSchema: { type: 'object', properties: { product_id: { type: 'string' } } },
  },
  {
    name: 'contact_submit',
    category: 'lead',
    scope: 'web',
    description: 'Soumission du formulaire contact (intent, avant validation lead)',
    isConversion: false,
    applicableCategories: ['form_submit'],
    defaultProviders: ['google_ga4'],
    paramsSchema: {
      type: 'object',
      properties: {
        form_id: { type: 'string' },
        method: { type: 'string' },
      },
    },
  },
  {
    name: 'newsletter_submit',
    category: 'lead',
    scope: 'web',
    description: 'Soumission du formulaire newsletter (intent, avant validation lead)',
    isConversion: false,
    applicableCategories: ['form_submit', 'newsletter'],
    defaultProviders: ['google_ga4'],
    paramsSchema: {
      type: 'object',
      properties: {
        form_id: { type: 'string' },
        list_name: { type: 'string' },
      },
    },
  },
  {
    name: 'video_user_play',
    category: 'engagement',
    scope: 'web',
    description: 'Lancement vid\u00e9o initi\u00e9 par l\u2019utilisateur (clic play). Distinct de l\u2019autoplay.',
    isConversion: false,
    applicableCategories: ['media_video'],
    defaultProviders: ['google_ga4', 'meta'],
    paramsSchema: {
      type: 'object',
      properties: { video_title: { type: 'string' }, video_duration: { type: 'number' } },
    },
  },
  {
    name: 'video_autoplay_view',
    category: 'engagement',
    scope: 'web',
    description: 'Lecture autoplay vue (\u2265 25 % de la vid\u00e9o), sans interaction utilisateur.',
    isConversion: false,
    applicableCategories: ['media_video'],
    defaultProviders: ['google_ga4'],
    paramsSchema: {
      type: 'object',
      properties: { video_title: { type: 'string' }, video_duration: { type: 'number' } },
    },
  },
  {
    name: 'form_field_focus',
    category: 'engagement',
    scope: 'web',
    description: 'Focus sur un champ de formulaire (premi\u00e8re interaction).',
    isConversion: false,
    applicableCategories: ['form_input'],
    defaultProviders: ['google_ga4'],
    paramsSchema: {
      type: 'object',
      required: ['form_id', 'field_name'],
      properties: { form_id: { type: 'string' }, field_name: { type: 'string' } },
    },
  },
  {
    name: 'form_field_blur',
    category: 'engagement',
    scope: 'web',
    description: 'Sortie d\u2019un champ de formulaire (avec valeur ou non).',
    isConversion: false,
    applicableCategories: ['form_input'],
    defaultProviders: ['google_ga4'],
    paramsSchema: {
      type: 'object',
      required: ['form_id', 'field_name'],
      properties: {
        form_id: { type: 'string' },
        field_name: { type: 'string' },
        has_value: { type: 'boolean' },
      },
    },
  },
  {
    name: 'form_validation_error',
    category: 'engagement',
    scope: 'web',
    description: 'Erreur de validation client sur un champ.',
    isConversion: false,
    applicableCategories: ['form_input', 'form_submit'],
    defaultProviders: ['google_ga4'],
    paramsSchema: {
      type: 'object',
      required: ['form_id', 'field_name'],
      properties: {
        form_id: { type: 'string' },
        field_name: { type: 'string' },
        error_code: { type: 'string' },
      },
    },
  },
  {
    name: 'form_abandon',
    category: 'engagement',
    scope: 'web',
    description: 'Abandon d\u2019un formulaire d\u00e9tect\u00e9 (pagehide ou navigation) avec champ touch\u00e9.',
    isConversion: false,
    applicableCategories: ['form_input', 'form_submit'],
    defaultProviders: ['google_ga4'],
    paramsSchema: {
      type: 'object',
      required: ['form_id'],
      properties: {
        form_id: { type: 'string' },
        last_field: { type: 'string' },
        time_on_form_ms: { type: 'number' },
      },
    },
  },
  {
    name: 'cta_impression',
    category: 'engagement',
    scope: 'web',
    description: 'Impression d\u2019un CTA (50 % visible, IntersectionObserver).',
    isConversion: false,
    applicableCategories: ['cta_primary', 'cta_secondary', 'cta_ghost'],
    defaultProviders: ['google_ga4'],
    paramsSchema: {
      type: 'object',
      required: ['cta_id'],
      properties: {
        cta_id: { type: 'string' },
        cta_text: { type: 'string' },
        cta_position: { type: 'string' },
      },
    },
  },
  {
    name: 'mini_cart_open',
    category: 'ecommerce',
    scope: 'web',
    description: 'Ouverture du mini-panier (drawer / popover).',
    isConversion: false,
    applicableCategories: ['commerce_cart'],
    defaultProviders: ['google_ga4'],
    paramsSchema: { type: 'object', properties: { trigger: { type: 'string' } } },
  },
  {
    name: 'mini_cart_close',
    category: 'ecommerce',
    scope: 'web',
    description: 'Fermeture du mini-panier.',
    isConversion: false,
    applicableCategories: ['commerce_cart'],
    defaultProviders: ['google_ga4'],
    paramsSchema: { type: 'object', properties: { trigger: { type: 'string' } } },
  },
  {
    name: 'video_transcript_open',
    category: 'engagement',
    scope: 'web',
    description: 'Ouverture de la transcription d\u2019une vid\u00e9o',
    isConversion: false,
    applicableCategories: ['media_video'],
    defaultProviders: ['google_ga4'],
    paramsSchema: {
      type: 'object',
      properties: {
        video_id: { type: 'string' },
        video_title: { type: 'string' },
      },
    },
  },
  {
    name: 'fg_pixel_test',
    category: 'admin',
    scope: 'both',
    description: '\u00c9v\u00e9nement de test pixel (dry-run admin)',
    isConversion: false,
    applicableCategories: ['admin'],
    defaultProviders: [],
    paramsSchema: { type: 'object', properties: { provider: { type: 'string' } } },
  },
  {
    name: 'fg_admin_action',
    category: 'admin',
    scope: 'server',
    description: 'Action admin (audit)',
    isConversion: false,
    applicableCategories: ['admin'],
    defaultProviders: [],
    paramsSchema: {
      type: 'object',
      required: ['action'],
      properties: { action: { type: 'string' }, resource: { type: 'string' } },
    },
  },
  {
    name: 'fg_consent_change',
    category: 'admin',
    scope: 'web',
    description: 'Mise \u00e0 jour du consent utilisateur',
    isConversion: false,
    applicableCategories: ['admin'],
    defaultProviders: [],
    paramsSchema: {
      type: 'object',
      properties: {
        ad_storage: { type: 'string' },
        analytics_storage: { type: 'string' },
        source: { type: 'string' },
      },
    },
  },

  // ===========================================================================
  // CHA-220 — \u00c9v\u00e9nements chat assistant (widget + lead capture in-chat).
  // Voir docs/chat-assistant/19-lead-capture-form.md \u00a77.
  // ===========================================================================
  {
    name: 'chat_widget_open',
    category: 'engagement',
    scope: 'web',
    description: 'Ouverture du widget chat assistant',
    isConversion: false,
    applicableCategories: ['chat'],
    defaultProviders: ['google_ga4', 'meta'],
    paramsSchema: {
      type: 'object',
      properties: {
        session_id: { type: 'string' },
        page_path: { type: 'string' },
        language: { type: 'string', enum: ['fr', 'ar', 'ar-MA'] },
        trigger: { type: 'string', enum: ['user', 'auto', 'cta'] },
      },
    },
  },
  {
    name: 'chat_widget_close',
    category: 'engagement',
    scope: 'web',
    description: 'Fermeture du widget chat assistant',
    isConversion: false,
    applicableCategories: ['chat'],
    defaultProviders: ['google_ga4'],
    paramsSchema: {
      type: 'object',
      properties: {
        session_id: { type: 'string' },
        messages_count: { type: 'number' },
        duration_ms: { type: 'number' },
      },
    },
  },
  {
    name: 'chat_message_sent',
    category: 'engagement',
    scope: 'web',
    description: 'Message envoy\u00e9 par le visiteur dans le chat',
    isConversion: false,
    applicableCategories: ['chat'],
    defaultProviders: ['google_ga4'],
    paramsSchema: {
      type: 'object',
      properties: {
        session_id: { type: 'string' },
        message_index: { type: 'number' },
        intent: { type: 'string' },
        chars: { type: 'number' },
      },
    },
  },
  {
    name: 'chat_message_received',
    category: 'engagement',
    scope: 'web',
    description: 'Premier token re\u00e7u en r\u00e9ponse (latence \u00e0 1\u1d49\u02b3 token)',
    isConversion: false,
    applicableCategories: ['chat'],
    defaultProviders: ['google_ga4'],
    paramsSchema: {
      type: 'object',
      properties: {
        session_id: { type: 'string' },
        message_id: { type: 'string' },
        first_token_ms: { type: 'number' },
      },
    },
  },
  {
    name: 'chat_message_complete',
    category: 'engagement',
    scope: 'web',
    description: 'R\u00e9ponse assistant compl\u00e8te (fin du stream)',
    isConversion: false,
    applicableCategories: ['chat'],
    defaultProviders: ['google_ga4'],
    paramsSchema: {
      type: 'object',
      properties: {
        session_id: { type: 'string' },
        message_id: { type: 'string' },
        latency_ms: { type: 'number' },
        tokens_out: { type: 'number' },
      },
    },
  },
  {
    name: 'chat_lead_form_offered',
    category: 'lead',
    scope: 'both',
    description: 'Offre proactive du formulaire de capture lead (SSE)',
    isConversion: false,
    applicableCategories: ['chat', 'form_submit'],
    defaultProviders: ['google_ga4'],
    paramsSchema: {
      type: 'object',
      properties: {
        session_id: { type: 'string' },
        message_id: { type: 'string' },
        reason: { type: 'string' },
        copy_key: { type: 'string' },
      },
    },
  },
  {
    name: 'chat_lead_form_view',
    category: 'lead',
    scope: 'web',
    description: 'Affichage du formulaire de capture lead in-chat',
    isConversion: false,
    applicableCategories: ['chat', 'form_submit'],
    defaultProviders: ['google_ga4'],
    paramsSchema: {
      type: 'object',
      properties: {
        session_id: { type: 'string' },
        reason: { type: 'string' },
      },
    },
  },
  {
    name: 'chat_lead_form_focus',
    category: 'lead',
    scope: 'web',
    description: 'Focus sur le premier champ (pr\u00e9nom) du formulaire lead',
    isConversion: false,
    applicableCategories: ['chat', 'form_submit'],
    defaultProviders: ['google_ga4'],
    paramsSchema: {
      type: 'object',
      properties: {
        session_id: { type: 'string' },
        field: { type: 'string' },
      },
    },
  },
  {
    name: 'chat_lead_form_dismiss',
    category: 'lead',
    scope: 'web',
    description: 'Le visiteur ferme le formulaire sans soumettre',
    isConversion: false,
    applicableCategories: ['chat', 'form_submit'],
    defaultProviders: ['google_ga4'],
    paramsSchema: {
      type: 'object',
      properties: {
        session_id: { type: 'string' },
        reason: { type: 'string' },
      },
    },
  },
  {
    name: 'chat_lead_form_submit',
    category: 'lead',
    scope: 'web',
    description: 'Tentative de soumission du formulaire lead in-chat',
    isConversion: false,
    applicableCategories: ['chat', 'form_submit'],
    defaultProviders: ['google_ga4'],
    paramsSchema: {
      type: 'object',
      properties: {
        session_id: { type: 'string' },
        reason: { type: 'string' },
      },
    },
  },
  {
    name: 'chat_lead_webhook_sent',
    category: 'lead',
    scope: 'server',
    description: 'Webhook lead envoy\u00e9 vers CRM/n8n (succ\u00e8s)',
    isConversion: false,
    applicableCategories: ['chat'],
    defaultProviders: [],
    paramsSchema: {
      type: 'object',
      properties: {
        lead_id: { type: 'string' },
        attempts: { type: 'number' },
      },
    },
  },
  {
    name: 'chat_lead_webhook_failed',
    category: 'lead',
    scope: 'server',
    description: 'Webhook lead en \u00e9chec apr\u00e8s 3 tentatives',
    isConversion: false,
    applicableCategories: ['chat'],
    defaultProviders: [],
    paramsSchema: {
      type: 'object',
      properties: {
        lead_id: { type: 'string' },
        reason: { type: 'string' },
      },
    },
  },

  // ===========================================================================
  // GTM-CHAT-001..003 \u2014 \u00c9v\u00e9nements UX chat suppl\u00e9mentaires (suggestions,
  // feedback, langue, erreur, rate-limit, attribution).
  // Voir docs/gtm/13-events-chat.md.
  // ===========================================================================
  {
    name: 'chat_suggestion_clicked',
    category: 'engagement',
    scope: 'web',
    description: 'Clic sur une suggestion contextuelle dans le chat',
    isConversion: false,
    applicableCategories: ['chat'],
    defaultProviders: ['google_ga4'],
    paramsSchema: {
      type: 'object',
      required: ['session_id', 'suggestion_label', 'suggestion_index'],
      properties: {
        session_id: { type: 'string' },
        suggestion_label: { type: 'string' },
        suggestion_index: { type: 'number' },
      },
    },
  },
  {
    name: 'chat_feedback',
    category: 'engagement',
    scope: 'web',
    description: 'Feedback (pouce vert/rouge) sur une r\u00e9ponse de l\u2019assistant',
    isConversion: false,
    applicableCategories: ['chat'],
    defaultProviders: ['google_ga4'],
    paramsSchema: {
      type: 'object',
      required: ['session_id', 'message_id', 'value'],
      properties: {
        session_id: { type: 'string' },
        message_id: { type: 'string' },
        value: { type: 'number', enum: [1, -1] },
        has_note: { type: 'boolean' },
      },
    },
  },
  {
    name: 'chat_language_switch',
    category: 'engagement',
    scope: 'web',
    description: 'Bascule de langue dans la conversation (FR / AR / Darija)',
    isConversion: false,
    applicableCategories: ['chat'],
    defaultProviders: ['google_ga4'],
    paramsSchema: {
      type: 'object',
      required: ['session_id', 'from_language', 'to_language', 'trigger'],
      properties: {
        session_id: { type: 'string' },
        from_language: { type: 'string', enum: ['fr', 'ar', 'ar-MA'] },
        to_language: { type: 'string', enum: ['fr', 'ar', 'ar-MA'] },
        trigger: { type: 'string', enum: ['auto_detect', 'user_request'] },
      },
    },
  },
  {
    name: 'chat_error',
    category: 'engagement',
    scope: 'web',
    description: 'Erreur visible c\u00f4t\u00e9 visiteur (provider down, mod\u00e9ration, timeout)',
    isConversion: false,
    applicableCategories: ['chat'],
    defaultProviders: ['google_ga4'],
    paramsSchema: {
      type: 'object',
      required: ['session_id', 'error_code'],
      properties: {
        session_id: { type: 'string' },
        error_code: {
          type: 'string',
          enum: [
            'rate_limited',
            'moderation_blocked_input',
            'moderation_blocked_output',
            'provider_unavailable',
            'quota_exceeded',
            'timeout',
            'internal',
          ],
        },
        message_id: { type: 'string' },
      },
    },
  },
  {
    name: 'chat_rate_limit_hit',
    category: 'engagement',
    scope: 'web',
    description: 'Le visiteur d\u00e9passe le rate-limit (par IP / session / visitor)',
    isConversion: false,
    applicableCategories: ['chat'],
    defaultProviders: ['google_ga4'],
    paramsSchema: {
      type: 'object',
      required: ['session_id', 'scope', 'retry_after_seconds'],
      properties: {
        session_id: { type: 'string' },
        scope: { type: 'string', enum: ['ip', 'session', 'visitor'] },
        retry_after_seconds: { type: 'number' },
      },
    },
  },
  {
    name: 'chat_conversion_attributed',
    category: 'custom',
    scope: 'both',
    description:
      'Signal d\u2019attribution chat \u2192 commande (audience-builder, pas une conversion en soi)',
    isConversion: false,
    applicableCategories: ['chat'],
    defaultProviders: ['google_ga4'],
    paramsSchema: {
      type: 'object',
      required: ['session_id', 'order_id', 'attribution_window_days', 'messages_in_session'],
      properties: {
        session_id: { type: 'string' },
        order_id: { type: 'string' },
        attribution_window_days: { type: 'number' },
        messages_in_session: { type: 'number' },
        intent_dominant: { type: 'string' },
      },
    },
  },
];

export function findEventInCatalog(name: string): EventCatalogEntry | null {
  return EVENT_CATALOG.find((e) => e.name === name) ?? null;
}
