import type { MediaWithRelations } from '@/lib/db/types';

const now = new Date('2026-01-01T00:00:00Z');

export function makeImageMedia(overrides: Partial<MediaWithRelations> = {}): MediaWithRelations {
  return {
    id: 'me_test123',
    kind: 'image',
    source: 'upload',
    slug: 'hero-test',
    originalUrl: '/_media/orig/test.jpg',
    originalFilename: 'test.jpg',
    originalSizeBytes: 1024,
    originalMime: 'image/jpeg',
    originalWidth: 1600,
    originalHeight: 900,
    originalDurationMs: null,
    phash: null,
    blurhash: null,
    palette: [{ r: 200, g: 180, b: 160, hex: '#c8b4a0', weight: 0.5 }],
    alt: 'Test image',
    caption: null,
    credit: null,
    status: 'ready',
    failureReason: null,
    qualityProfile: 'inline',
    loadingStrategy: 'viewport',
    isHero: false,
    overrides: {},
    createdBy: null,
    createdAt: now,
    updatedAt: now,
    deletedAt: null,
    variants: [
      {
        id: 'mv_jpeg_sm',
        mediaId: 'me_test123',
        format: 'jpeg',
        breakpoint: 'sm',
        width: 480,
        height: 270,
        bitrateKbps: null,
        quality: 80,
        sizeBytes: 200,
        url: '/_media/test-480.jpg',
        checksum: 'a',
        createdAt: now,
      },
      {
        id: 'mv_jpeg_lg',
        mediaId: 'me_test123',
        format: 'jpeg',
        breakpoint: 'lg',
        width: 1024,
        height: 576,
        bitrateKbps: null,
        quality: 80,
        sizeBytes: 500,
        url: '/_media/test-1024.jpg',
        checksum: 'b',
        createdAt: now,
      },
      {
        id: 'mv_webp_lg',
        mediaId: 'me_test123',
        format: 'webp',
        breakpoint: 'lg',
        width: 1024,
        height: 576,
        bitrateKbps: null,
        quality: 75,
        sizeBytes: 300,
        url: '/_media/test-1024.webp',
        checksum: 'c',
        createdAt: now,
      },
      {
        id: 'mv_avif_lg',
        mediaId: 'me_test123',
        format: 'avif',
        breakpoint: 'lg',
        width: 1024,
        height: 576,
        bitrateKbps: null,
        quality: 55,
        sizeBytes: 200,
        url: '/_media/test-1024.avif',
        checksum: 'd',
        createdAt: now,
      },
    ],
    tags: [],
    ...overrides,
  };
}

export function makeVideoMedia(overrides: Partial<MediaWithRelations> = {}): MediaWithRelations {
  return {
    ...makeImageMedia(),
    kind: 'video',
    slug: 'video-test',
    originalMime: 'video/mp4',
    originalDurationMs: 30000,
    variants: [
      {
        id: 'mv_mp4',
        mediaId: 'me_test123',
        format: 'mp4',
        breakpoint: null,
        width: 1280,
        height: 720,
        bitrateKbps: 2500,
        quality: null,
        sizeBytes: 500000,
        url: '/_media/test.mp4',
        checksum: 'e',
        createdAt: now,
      },
      {
        id: 'mv_webm',
        mediaId: 'me_test123',
        format: 'webm',
        breakpoint: null,
        width: 1280,
        height: 720,
        bitrateKbps: 2000,
        quality: null,
        sizeBytes: 400000,
        url: '/_media/test.webm',
        checksum: 'f',
        createdAt: now,
      },
      {
        id: 'mv_poster',
        mediaId: 'me_test123',
        format: 'poster',
        breakpoint: null,
        width: 1280,
        height: 720,
        bitrateKbps: null,
        quality: null,
        sizeBytes: 50000,
        url: '/_media/poster.jpg',
        checksum: 'g',
        createdAt: now,
      },
    ],
    ...overrides,
  };
}

export function makeAudioMedia(overrides: Partial<MediaWithRelations> = {}): MediaWithRelations {
  return {
    ...makeImageMedia(),
    kind: 'audio',
    slug: 'audio-test',
    originalMime: 'audio/mpeg',
    originalDurationMs: 60000,
    originalWidth: null,
    originalHeight: null,
    variants: [
      {
        id: 'mv_mp3',
        mediaId: 'me_test123',
        format: 'mp3',
        breakpoint: null,
        width: null,
        height: null,
        bitrateKbps: 128,
        quality: null,
        sizeBytes: 1024000,
        url: '/_media/test.mp3',
        checksum: 'h',
        createdAt: now,
      },
      {
        id: 'mv_opus',
        mediaId: 'me_test123',
        format: 'opus',
        breakpoint: null,
        width: null,
        height: null,
        bitrateKbps: 96,
        quality: null,
        sizeBytes: 700000,
        url: '/_media/test.opus',
        checksum: 'i',
        createdAt: now,
      },
    ],
    ...overrides,
  };
}
